title: Landing Page(Data Visualization)
description:  The process of using visual elements like charts, graphs, or maps to represent data.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
