title: Landing Page(Data Visualization)
description:  The process of using visual elements like charts, graphs, or maps to represent data.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
